import Head from 'next/head'
import { Flex, Text } from '@chakra-ui/react'

function HomePage() {
	return (
		<Flex>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Text>Homepage</Text>
		</Flex>
	)
}

export default HomePage
