// Social icons
export { default as FacebookIcon } from './social/facebook-icon'
export { default as GithubIcon } from './social/github-icon'
export { default as GmailIcon } from './social/gmail-icon'
export { default as LinkedInIcon } from './social/linkedin-icon'
export { default as TwitterIcon } from './social/twitter-icon'
export { default as WhatsappIcon } from './social/whatsapp-icon'

// Technologies icons
export { default as AngularIcon } from './technologies/angular-icon'
export { default as BootstrapIcon } from './technologies/bootstrap-icon'
export { default as CIcon } from './technologies/c-icon'
export { default as ChartJsIcon } from './technologies/chart-js-icon'
export { default as DockerIcon } from './technologies/docker-icon'
export { default as ExpressIcon } from './technologies/express-icon'
export { default as JavaIcon } from './technologies/java-icon'
export { default as JavascriptIcon } from './technologies/javascript-icon'
export { default as KotlinIcon } from './technologies/kotlin-icon'
export { default as MaterialUiIcon } from './technologies/material-ui-icon'
export { default as MongoIcon } from './technologies/mongo-icon'
export { default as MySqlIcon } from './technologies/my-sql-icon'
export { default as NestIcon } from './technologies/nest-icon'
export { default as NextIcon } from './technologies/next-icon'
export { default as NodeIcon } from './technologies/node-icon'
export { default as PostgreIcon } from './technologies/postgre-icon'
export { default as ReactIcon } from './technologies/react-icon'
export { default as ReduxIcon } from './technologies/redux-icon'
export { default as SassIcon } from './technologies/sass-icon'
export { default as SpringIcon } from './technologies/spring-icon'
export { default as StrapiIcon } from './technologies/strapi-icon'
export { default as SwaggerIcon } from './technologies/swagger-icon'
export { default as TailwindIcon } from './technologies/tailwind-icon'
export { default as TypescriptIcon } from './technologies/typescript-icon'
export { default as VueIcon } from './technologies/vue-icon'
export { default as VueMaterialIcon } from './technologies/vue-material-icon'
export { default as TechIcon } from './technologies/tech-icon'

// Application icons
export { default as ArrowIcon } from './arrow-icon'
export { default as BookmarkIcon } from './bookmark-icon'
export { default as BrasilFlagIcon } from './brasil-flag-icon'
export { default as CalendarIcon } from './calendar-icon'
export { default as ClockIcon } from './clock-icon'
export { default as CommentIcon } from './comment-icon'
export { default as HeartIcon } from './heart-icon'
export { default as HomeIcon } from './home-icon'
export { default as LayoutIcon } from './layout-icon'
export { default as Logo } from './logo'
export { default as MenuIcon } from './menu-icon'
export { default as SearchIcon } from './search-icon'
export { default as ShareIcon } from './share-icon'
export { default as UsaFlagIcon } from './usa-flag-icon'
